apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-microservice-v4
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://CE696177C24A30341CBDA5BB7B9A29D4.gr7.us-east-2.eks.amazonaws.com
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/iamahgoub/sample-microservice-manifests.git
    targetRevision: v4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
